[build]
  base = "kidzkapers"       # Netlify will cd into this folder first
  command = "npm install && npm run build"
  publish = "dist"  # Where the built files are

[build.environment]
  NODE_VERSION = "18"